// Cross-implementation parity: the mobile engine is a hand-port of the desktop
// Python engine (benchmark/correct_herbs.py + pipeline.py), and this test runs
// BOTH on identical transcripts. The expected values in fixtures/parity.json
// are generated by the Python engine -- regenerate with:
//     python benchmark/tests/generate_parity_fixtures.py
// A failure here means the two implementations have drifted apart: decide which
// is right, then fix the other. Never edit parity.json by hand.

import { runPipeline } from '../src/runPipeline';
import fixtures from './fixtures/parity.json';

type Herb = { name: string; dosage: number; ambiguous: boolean; ambiguousWith: string | null };
type Point = { name: string; laterality: string | null; ambiguous: boolean; ambiguousWith: string | null };
type Fixture = { input: string; prescriptionSectionFound: boolean; herbs: Herb[]; points: Point[] };

const cases = Object.entries(fixtures as Record<string, Fixture>);

describe('mobile engine matches the desktop Python engine', () => {
  it.each(cases)('%s', (_name, expected) => {
    const out = runPipeline(expected.input);

    expect(out.prescriptionSectionFound).toBe(expected.prescriptionSectionFound);
    expect(
      out.herbs.map(h => ({ name: h.name, dosage: h.dosage, ambiguous: h.ambiguous, ambiguousWith: h.ambiguousWith ?? null })),
    ).toEqual(expected.herbs);
    expect(
      out.points.map(p => ({ name: p.name, laterality: p.laterality, ambiguous: p.ambiguous, ambiguousWith: p.ambiguousWith ?? null })),
    ).toEqual(expected.points);
  });
});
